version: '3'
services:
  server:
    build:
      context: .
      dockerfile: nginx.dev.Dockerfile
    image: nginx-server
    ports:
      - '80:80'
    links: 
      - api:api
      - app:app
  app:
    build:
      context: .
      dockerfile: app.dev.Dockerfile
    image: app-server
    environment:
      - NODE_ENV=development
    volumes:
      - ./app:/var/www/app
    ports:
      - '3000:3000'
  api:
    build:
      context: .
      dockerfile: api.dev.Dockerfile
    image: api-server
    environment:
      - DB_NAME=appdb
      - DB_USER=appuser
      - DB_PASSWORD=apppassword
      - DB_HOST="db"
      - DB_HOST=5432
      - NODE_ENV=development
    links:
      - db:db
    volumes:
      - ./api:/var/www/api
      - ./api/node_modules:/var/www/api/node_modules
    ports:
      - '8080'
    depends_on:
      - 'db'
  db:
    build:
      context: .
      dockerfile: db.dev.Dockerfile
    env_file: psql.env
    image: app-db
    ports:
      - '5431:5432'
